apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
      - name: go-backend
        image: ozaitsev92/go-todo-app:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: backend-config-volume
          mountPath: /config/config.toml
          subPath: config.toml
      volumes:
      - name: backend-config-volume
        configMap:
          name: backend-config