version: "3.9"
services:
  todoapp_client:
    container_name: todoapp_client
    restart: always
    build:
      dockerfile: Dockerfile
      context: frontend
    ports:
      - "8081:80"
    depends_on:
      - todoapp_server
    networks:
      - todoapp_network

  todoapp_server:
    container_name: todoapp_server
    restart: always
    build:
      dockerfile: Dockerfile
      context: backend
    ports:
      - "8080:8080"
    depends_on:
      - todoapp_mongodb
    networks:
      - todoapp_network

  todoapp_mongodb:
    container_name: todoapp_mongodb
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - todoapp_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - todoapp_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - todoapp_network

networks:
  todoapp_network:

volumes:
  prometheus:
    driver: local
  grafana:
    driver: local
