version: "3.9"
services:
  todoapp_client:
    container_name: todoapp_client
    restart: always
    build:
      dockerfile: Dockerfile
      context: frontend
    ports:
      - "3000:80"
    depends_on:
      - todoapp_server
    networks:
      - todoapp_network

  todoapp_server:
    container_name: todoapp_server
    restart: always
    build:
      dockerfile: Dockerfile
      context: backend
    ports:
      - "8080:8080"
    depends_on:
      - todoapp_mongodb
    networks:
      - todoapp_network

  todoapp_mongodb:
    container_name: todoapp_mongodb
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - todoapp_network

networks:
  todoapp_network:
