version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    networks:
      - todoapp_network

  todoapp:
    container_name: todoapp
    restart: always
    build:
      dockerfile: Dockerfile
      context: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - todoapp_network

networks:
  todoapp_network: