version: "3.9"
services:
  # todoapp_postgres:
  #   container_name: todoapp_postgres
  #   image: postgres
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: todo_db
  #   networks:
  #     - todoapp_network
  #   healthcheck:
  #     test: [ "CMD-SHELL", "sh -c 'pg_isready -U user -d todo_db'" ]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 3

  todoapp_client:
    container_name: todoapp_client
    restart: always
    build:
      dockerfile: Dockerfile
      context: frontend
    ports:
      - "3000:80"
    depends_on:
      - todoapp_server
    networks:
      - todoapp_network

  todoapp_server:
    container_name: todoapp_server
    restart: always
    build:
      dockerfile: Dockerfile
      context: backend-new
    ports:
      - "8080:8080"
    # depends_on:
    #   - todoapp_postgres
    networks:
      - todoapp_network

networks:
  todoapp_network:
