bind_addr = "8080"
log_level = "debug"
mongo_url = "mongodb://localhost:27017"
mongo_db_name = "todo"
session_key = "350401be75bbb0fafd3d912a1a1d5e54"
write_timeout = 15
read_timeout = 15
idle_timeout = 60
graceful_timeout = 15

jwt_signing_key = "go-todo-app"
jwt_session_length = 30
jwt_cookie_domain = "localhost"
jwt_secure_cookie = true

allowed_origin = "http://localhost:3000"
