bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost dbname=todo_db sslmode=disable user=user password=password"
session_key = "350401be75bbb0fafd3d912a1a1d5e54"
write_timeout = 15
read_timeout = 15
idle_timeout = 60
graceful_timeout = 15