name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        go: [1.23.3]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      - name: Verify Docker Installation
        run: docker --version

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3

      - name: Install dependencies
        working-directory: backend
        run: go mod tidy

      - name: Build
        working-directory: backend
        run: go build -v ./cmd/app

      - name: Run Tests
        working-directory: backend
        env:
          MONGO_URI: mongodb://localhost:27017
        run: go test -v ./...

      - name: Debug Secrets
        run: |
          echo "DOCKER_USERNAME: ${DOCKER_USERNAME:-not set}"
          echo "DOCKER_TOKEN is set: ${DOCKER_TOKEN:+yes}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker Image
        working-directory: backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/go-todo-app:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/go-todo-app:latest
