name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        go: [1.23.3]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker (if not available)
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3

      - name: Install dependencies
        run: go mod tidy -C backend

      - name: Build
        run: go build -C backend -v ./cmd/app

      - name: Run Tests
        env:
          MONGO_URI: mongodb://localhost:27017
        run: go test -C backend -v ./...
